server:
  host: localhost
  port: 7777

mysql:
  username: offertown_dev
  password: offertown_dev_password
  host: localhost
  port: 3306
  database_name: offertown_database_dev

argon2:
  times: 3
  memory: 65535
  threads: 2
  keyLen: 32

jwt:
  secret: justATestSecret

redis:
  host: localhost
  port: 6379
  password: